#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 29 16:50:17 2017

@author: estelleaflalo
"""

import glob
import pandas as pd
import re
import os
import shutil

pathname="/Users/estelleaflalo/Desktop/M2_Data_Science/First_Period/Machine_Learning_from_Theory_to_Practice/Project/challenge_fichier_dentrees_dentrainement_predire_le_score_esthetique_dun_portrait/pictures_train2/*.jpg"


numbers = re.compile(r'(\d+)')

def numericalSort(value):
    parts = numbers.split(value)
    parts[1::2] = map(int, parts[1::2])
    return parts

i=1 
pathresult = "/Users/estelleaflalo/Desktop/M2_Data_Science/First_Period/Machine_Learning_from_Theory_to_Practice/Project/challenge_fichier_de_sortie_dentrainement_predire_le_score_esthetique_dun_portrait.csv"
y_df = pd.read_csv( pathresult, sep = ';')

for img in sorted(glob.glob(pathname), key=numericalSort):
    old_name="/Users/estelleaflalo/Desktop/M2_Data_Science/First_Period/Machine_Learning_from_Theory_to_Practice/Project/challenge_fichier_dentrees_dentrainement_predire_le_score_esthetique_dun_portrait/pictures_train2/"
    new_name=old_name+str(y_df['TARGET'][i-1]) 
    #print (img)
    shutil.move(img, new_name)
    i=i+1
    
    




print(3)